In [1]:
import numpy as np

## In-built functiona

### np.zeros()

In [4]:
np.zeros(5)    # will return 1D

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))    # 2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4,5))     # 3 such matrix or array wit 4X5( 4rows and 5 columns)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

###   scalar quantity adding with vecor quantity
- scalor --->> has only magnitude no direction, one dimentional -----> here 5 is scalar quantity 

- vector---->> has bith magnitute and direction, multi dimentional -----> here an array(matrix) is a vector qualntity 

###  broadcasting, 
 broadcasting- (one single entity available for all the entities) or performing single oeration on all the entities

In [15]:

5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

### ones() 

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
2*np.ones((3,5))

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## empty()
- will give u very ery small no close to zero  
- everyone will recieve different differnt values

In [20]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69120824e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.60220393e-306, 7.56589622e-307],
       [1.33510882e-306, 1.37961370e-306, 1.69118515e-306,
        7.56598449e-307, 1.42410974e-306]])

### np.linespace()
- it take starting point end points and it will genrate values in between
- they include upper bound also like if range is between (1,1.5) 1.5 will be included.

### Que: genrate millions of no between 1 and 1.5

In [27]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

## difference between arange and linespace()
- arange()- it will genrate the no between given range and as per ur stepsize
- linespace()- it will genrate as much as no u want ;like between 1 and 2.5 if u want to genrate 10000 of number it can genrate.it will divide the given no in given range (i.e 1,2.5)

In [41]:
a=np.linspace(1,2.5,50)
a

array([1.        , 1.03061224, 1.06122449, 1.09183673, 1.12244898,
       1.15306122, 1.18367347, 1.21428571, 1.24489796, 1.2755102 ,
       1.30612245, 1.33673469, 1.36734694, 1.39795918, 1.42857143,
       1.45918367, 1.48979592, 1.52040816, 1.55102041, 1.58163265,
       1.6122449 , 1.64285714, 1.67346939, 1.70408163, 1.73469388,
       1.76530612, 1.79591837, 1.82653061, 1.85714286, 1.8877551 ,
       1.91836735, 1.94897959, 1.97959184, 2.01020408, 2.04081633,
       2.07142857, 2.10204082, 2.13265306, 2.16326531, 2.19387755,
       2.2244898 , 2.25510204, 2.28571429, 2.31632653, 2.34693878,
       2.37755102, 2.40816327, 2.43877551, 2.46938776, 2.5       ])

### Que- convert a into 2 dimensions:

In [42]:
a.reshape(25,2)

array([[1.        , 1.03061224],
       [1.06122449, 1.09183673],
       [1.12244898, 1.15306122],
       [1.18367347, 1.21428571],
       [1.24489796, 1.2755102 ],
       [1.30612245, 1.33673469],
       [1.36734694, 1.39795918],
       [1.42857143, 1.45918367],
       [1.48979592, 1.52040816],
       [1.55102041, 1.58163265],
       [1.6122449 , 1.64285714],
       [1.67346939, 1.70408163],
       [1.73469388, 1.76530612],
       [1.79591837, 1.82653061],
       [1.85714286, 1.8877551 ],
       [1.91836735, 1.94897959],
       [1.97959184, 2.01020408],
       [2.04081633, 2.07142857],
       [2.10204082, 2.13265306],
       [2.16326531, 2.19387755],
       [2.2244898 , 2.25510204],
       [2.28571429, 2.31632653],
       [2.34693878, 2.37755102],
       [2.40816327, 2.43877551],
       [2.46938776, 2.5       ]])

## v.important - if we dont want to see upper bound in linspace , then add endpoint= False

In [45]:
a=np.linspace(1,2.5,50,endpoint=False)

In [48]:
a

array([1.  , 1.03, 1.06, 1.09, 1.12, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3 ,
       1.33, 1.36, 1.39, 1.42, 1.45, 1.48, 1.51, 1.54, 1.57, 1.6 , 1.63,
       1.66, 1.69, 1.72, 1.75, 1.78, 1.81, 1.84, 1.87, 1.9 , 1.93, 1.96,
       1.99, 2.02, 2.05, 2.08, 2.11, 2.14, 2.17, 2.2 , 2.23, 2.26, 2.29,
       2.32, 2.35, 2.38, 2.41, 2.44, 2.47])

## linspace never consider the stepsize but to distribute data in given numbers , it takes find out step size, what step size system has genrated 

In [49]:
np.linspace(1,2.5,50,endpoint=False,retstep= True)

(array([1.  , 1.03, 1.06, 1.09, 1.12, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3 ,
        1.33, 1.36, 1.39, 1.42, 1.45, 1.48, 1.51, 1.54, 1.57, 1.6 , 1.63,
        1.66, 1.69, 1.72, 1.75, 1.78, 1.81, 1.84, 1.87, 1.9 , 1.93, 1.96,
        1.99, 2.02, 2.05, 2.08, 2.11, 2.14, 2.17, 2.2 , 2.23, 2.26, 2.29,
        2.32, 2.35, 2.38, 2.41, 2.44, 2.47]),
 0.03)

## logspace()

##### the only differce in between linsapce and lospace is it will calculate the logerithmic of the number 

In [50]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [52]:
a= np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
a1=np.arange(4,20).reshape(4,2,2)
a1

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [60]:
a1.max()

19

### very important

In [68]:
a1.max(axis=1)      # column wise search

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [69]:
a1.max(axis=0)

array([[16, 17],
       [18, 19]])

In [74]:
a3=np.arange(36).reshape(6,6)
a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
a3.max(axis=0)     # row wise 

array([30, 31, 32, 33, 34, 35])

In [78]:
a3.max(axis=1)      # column wise 

array([ 5, 11, 17, 23, 29, 35])

In [79]:
a3


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### cube or power of a number

In [80]:
a3**3

array([[    0,     1,     8,    27,    64,   125],
       [  216,   343,   512,   729,  1000,  1331],
       [ 1728,  2197,  2744,  3375,  4096,  4913],
       [ 5832,  6859,  8000,  9261, 10648, 12167],
       [13824, 15625, 17576, 19683, 21952, 24389],
       [27000, 29791, 32768, 35937, 39304, 42875]], dtype=int32)

In [81]:
pow(a3,3)

array([[    0,     1,     8,    27,    64,   125],
       [  216,   343,   512,   729,  1000,  1331],
       [ 1728,  2197,  2744,  3375,  4096,  4913],
       [ 5832,  6859,  8000,  9261, 10648, 12167],
       [13824, 15625, 17576, 19683, 21952, 24389],
       [27000, 29791, 32768, 35937, 39304, 42875]], dtype=int32)

### row wise broadcasting

In [82]:
a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [83]:
b3=np.array([2,4,6,8,3,2])

In [85]:
a3+b3  # row wise broadcasting

array([[ 2,  5,  8, 11,  7,  7],
       [ 8, 11, 14, 17, 13, 13],
       [14, 17, 20, 23, 19, 19],
       [20, 23, 26, 29, 25, 25],
       [26, 29, 32, 35, 31, 31],
       [32, 35, 38, 41, 37, 37]])

### column wise broadcasting
- firstly do Transpose of an array- this we can do into 2d, 3d ...... not on one d

In [89]:
a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [94]:
b3=np.array([2,4,6,8,3,2])

In [99]:
b3=b3.reshape(1,6)        #or b3.reshape(1,-1)

In [100]:
b3

array([[2, 4, 6, 8, 3, 2]])

In [104]:
b3=b3.T        # transpose
b3

array([[2],
       [4],
       [6],
       [8],
       [3],
       [2]])

In [107]:
l1=a3+b3
l1

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [27, 28, 29, 30, 31, 32],
       [32, 33, 34, 35, 36, 37]])

In [108]:
l1.T   # transpose

array([[ 2, 10, 18, 26, 27, 32],
       [ 3, 11, 19, 27, 28, 33],
       [ 4, 12, 20, 28, 29, 34],
       [ 5, 13, 21, 29, 30, 35],
       [ 6, 14, 22, 30, 31, 36],
       [ 7, 15, 23, 31, 32, 37]])

#### another way of doing this is , firstly transpose the a3 then add b3, again transpose the whole matrix to get the column wise addition, as we can do the transpose of 2d,3d,4d........ matrix or array only 

In [113]:
b4=np.array([2,4,6,8,3,2])
b4

array([2, 4, 6, 8, 3, 2])

In [117]:
a4=a3.T
a4

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [120]:
n=a4+b4
n

array([[ 2, 10, 18, 26, 27, 32],
       [ 3, 11, 19, 27, 28, 33],
       [ 4, 12, 20, 28, 29, 34],
       [ 5, 13, 21, 29, 30, 35],
       [ 6, 14, 22, 30, 31, 36],
       [ 7, 15, 23, 31, 32, 37]])

In [121]:
n.T

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [27, 28, 29, 30, 31, 32],
       [32, 33, 34, 35, 36, 37]])

### square root of an array

In [124]:
a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [123]:
np.sqrt(a3)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152],
       [4.89897949, 5.        , 5.09901951, 5.19615242, 5.29150262,
        5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
        5.91607978]])

### exponent

In [126]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

### log

In [129]:
np.log10(a3)

C:\Users\apsgo\AppData\Local\Temp\ipykernel_13716\1655526489.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a3)


array([[      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
        0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
        1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126, 1.20411998,
        1.23044892],
       [1.25527251, 1.2787536 , 1.30103   , 1.32221929, 1.34242268,
        1.36172784],
       [1.38021124, 1.39794001, 1.41497335, 1.43136376, 1.44715803,
        1.462398  ],
       [1.47712125, 1.49136169, 1.50514998, 1.51851394, 1.53147892,
        1.54406804]])

## deepcopy- 
- it  will copy the data to the differnt loaction and there will not be any kind of dependency. 
- x=[1,2,3,4,5]       
- z=np.copy(x)
-both of them having diffent differnt memory address. 

if we will make the change to the x it eill not gonna make any changes in z because of the diifernt memory address 

In [165]:
x= np.array([1,2,3,4,5,6])

In [166]:
z=np.copy(x)
z

array([1, 2, 3, 4, 5, 6])

In [167]:
t=x.copy()
t

array([1, 2, 3, 4, 5, 6])

In [168]:
x[0]=100
x

array([100,   2,   3,   4,   5,   6])

In [169]:
t

array([1, 2, 3, 4, 5, 6])

In [170]:
z     # no changes 

array([1, 2, 3, 4, 5, 6])

##  shollow -copy 
- here bothe x and y have the same memory address, and there is complete depency on each other if will make the change in one the changes will reflect in another one for sure.
- x=y ( same memory allocation)
- hence if will make the change in x or y , it definalty will make the chages in y and x, this is called as shollow cpy

see example:

In [148]:
x= np.array([1,2,3,4,5,6])

In [149]:
y=x

In [150]:
y

array([1, 2, 3, 4, 5, 6])

In [152]:
y[0]=100

In [153]:
y

array([100,   2,   3,   4,   5,   6])

In [154]:
x

array([100,   2,   3,   4,   5,   6])

## Id() 
- identity of an objects
- this is gaurnteed to be un unique among simultaneously existing objects.

In [155]:
id(x)

1968285124432

In [156]:
id(y)

1968285124432

In [157]:
id(x[0])

1968283871472

In [158]:
id(y[0])

1968283871664

In [159]:
id(x[0])==id(y[0])

True

### view()

In [172]:
x

array([100,   2,   3,   4,   5,   6])

In [174]:
m=x.view()
m

array([100,   2,   3,   4,   5,   6])

In [175]:
x[1]=101

In [176]:
x

array([100, 101,   3,   4,   5,   6])

In [177]:
m

array([100, 101,   3,   4,   5,   6])

## slicing

In [179]:
a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [180]:
a3[1,2]

8

In [186]:
a3[:,1]

array([ 1,  7, 13, 19, 25, 31])

In [195]:
a3[[1,2,3,4,5],:]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### ravel() 
- to flatten the dictionary

In [233]:
a3

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [235]:
a3.ravel()

array([ 0,  6, 12, 18, 24, 30,  1,  7, 13, 19, 25, 31,  2,  8, 14, 20, 26,
       32,  3,  9, 15, 21, 27, 33,  4, 10, 16, 22, 28, 34,  5, 11, 17, 23,
       29, 35])

In [214]:
a3

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [205]:
a3=a4
a4

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

### insert()

In [210]:
np.insert(a4,2,7)

array([ 0,  6,  7, 12, 18, 24, 30,  1,  7, 13, 19, 25, 31,  2,  8, 14, 20,
       26, 32,  3,  9, 15, 21, 27, 33,  4, 10, 16, 22, 28, 34,  5, 11, 17,
       23, 29, 35])

### append()

In [212]:
bn=[3,4,5,6,7,9]

In [216]:
t=np.append(bn,a3)
t

array([ 3,  4,  5,  6,  7,  9,  0,  6, 12, 18, 24, 30,  1,  7, 13, 19, 25,
       31,  2,  8, 14, 20, 26, 32,  3,  9, 15, 21, 27, 33,  4, 10, 16, 22,
       28, 34,  5, 11, 17, 23, 29, 35])

In [224]:
p=t.reshape(7,-1)
p

array([[ 3,  4,  5,  6,  7,  9],
       [ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [230]:
s=np.append(bn,p)
s

array([ 3,  4,  5,  6,  7,  9,  3,  4,  5,  6,  7,  9,  0,  6, 12, 18, 24,
       30,  1,  7, 13, 19, 25, 31,  2,  8, 14, 20, 26, 32,  3,  9, 15, 21,
       27, 33,  4, 10, 16, 22, 28, 34,  5, 11, 17, 23, 29, 35])

In [262]:
s=s.reshape(6,-1)
s

array([[ 3,  4,  5,  6,  7,  9,  3,  4],
       [ 5,  6,  7,  9,  0,  6, 12, 18],
       [24, 30,  1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32,  3,  9],
       [15, 21, 27, 33,  4, 10, 16, 22],
       [28, 34,  5, 11, 17, 23, 29, 35]])

## stack()

In [242]:
a=np.array([ 3,  4,  5,  6,  7,  9,  3,  4])
b=np.array( [ 5,  6,  7,  9,  0,  6, 12, 18])

In [252]:
np.column_stack((a,b))

array([[ 3,  5],
       [ 4,  6],
       [ 5,  7],
       [ 6,  9],
       [ 7,  0],
       [ 9,  6],
       [ 3, 12],
       [ 4, 18]])

In [253]:
np.c_[a,b]

array([[ 3,  5],
       [ 4,  6],
       [ 5,  7],
       [ 6,  9],
       [ 7,  0],
       [ 9,  6],
       [ 3, 12],
       [ 4, 18]])

In [254]:
np.row_stack((a,b))

array([[ 3,  4,  5,  6,  7,  9,  3,  4],
       [ 5,  6,  7,  9,  0,  6, 12, 18]])

In [256]:
np.r_[a,b]

array([ 3,  4,  5,  6,  7,  9,  3,  4,  5,  6,  7,  9,  0,  6, 12, 18])

In [257]:
np.hstack((a,b))

array([ 3,  4,  5,  6,  7,  9,  3,  4,  5,  6,  7,  9,  0,  6, 12, 18])

In [259]:
np.vstack((a,b))

array([[ 3,  4,  5,  6,  7,  9,  3,  4],
       [ 5,  6,  7,  9,  0,  6, 12, 18]])

array([ 3,  4,  5,  6,  7,  9,  3,  4,  5,  6,  7,  9,  0,  6, 12, 18, 24,
       30,  1,  7, 13, 19, 25, 31,  2,  8, 14, 20, 26, 32,  3,  9, 15, 21,
       27, 33,  4, 10, 16, 22, 28, 34,  5, 11, 17, 23, 29, 35])

In [263]:
s

array([[ 3,  4,  5,  6,  7,  9,  3,  4],
       [ 5,  6,  7,  9,  0,  6, 12, 18],
       [24, 30,  1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32,  3,  9],
       [15, 21, 27, 33,  4, 10, 16, 22],
       [28, 34,  5, 11, 17, 23, 29, 35]])

## split()

In [265]:
np.vsplit(s,3)

[array([[ 3,  4,  5,  6,  7,  9,  3,  4],
        [ 5,  6,  7,  9,  0,  6, 12, 18]]),
 array([[24, 30,  1,  7, 13, 19, 25, 31],
        [ 2,  8, 14, 20, 26, 32,  3,  9]]),
 array([[15, 21, 27, 33,  4, 10, 16, 22],
        [28, 34,  5, 11, 17, 23, 29, 35]])]

In [266]:
np.hsplit(s,4)

[array([[ 3,  4],
        [ 5,  6],
        [24, 30],
        [ 2,  8],
        [15, 21],
        [28, 34]]),
 array([[ 5,  6],
        [ 7,  9],
        [ 1,  7],
        [14, 20],
        [27, 33],
        [ 5, 11]]),
 array([[ 7,  9],
        [ 0,  6],
        [13, 19],
        [26, 32],
        [ 4, 10],
        [17, 23]]),
 array([[ 3,  4],
        [12, 18],
        [25, 31],
        [ 3,  9],
        [16, 22],
        [29, 35]])]