In [7]:
import numpy as np

In [17]:
l=["tavi","sanna",2,3,4,56,8,]

In [18]:
type(l)

list

### To change list linto arrany 

In [19]:
np.array(l)                                                                    #dtype='<U11') this is datatype of data type 

array(['tavi', 'sanna', '2', '3', '4', '56', '8'], dtype='<U11')

In [20]:
type(np.array(l) )   #ndarray- ndimentions array 

numpy.ndarray

In [23]:
np.array([2,3,3,4,5,6,7,8.9]) # by default it will convert to floating no as, one float no is available (we call it type casting )

array([2. , 3. , 3. , 4. , 5. , 6. , 7. , 8.9])

In [37]:
a=np.array([[2,3,4,8],[3,7,5,6]])  # inside this we have two list 
a                                         

array([[2, 3, 4, 8],
       [3, 7, 5, 6]])

In [303]:
a=[2,3,4,8]
np.array(a)

array([2, 3, 4, 8])

#### extract 8 

In [38]:
a[0,3]         # 0 indicates rows and 2 indicates column i.e (a[Row number, column number])

8

#### Extract 7

In [40]:
a[1,1]

7

### Dimentions

##### 1D

In [49]:
np.array([2,3,4,8],ndmin=0)

array([2, 3, 4, 8])

In [50]:
np.array([2,3,4,8],ndmin=1)

array([2, 3, 4, 8])

#### 2D

In [51]:
np.array([2,3,4,8],ndmin=2)   # bracket increse by 2

array([[2, 3, 4, 8]])

#### 3D

In [57]:
b=np.array([2,3,4,8],ndmin=3) # bracket inncreased by 3
b

array([[[2, 3, 4, 8]]])

In [63]:
# extract 4
b[0][0][2]


4

#### 4D

In [58]:
c=np.array([2,3,4,8],ndmin=4)      
c

array([[[[2, 3, 4, 8]]]])

In [65]:
# extract 8
c[0][0][0][3]

8

## np.mat()            
- Here mat is matrix - matrix are nothing but will return 2D array ven at 0 min 
- matrix is subclass or child class of an array.

In [80]:
np.mat([4,5,6,8,6])          # by default this will return 2d

matrix([[4, 5, 6, 8, 6]])

In [116]:
c=np.array([2,3,4,8],ndmin=4)      
c

array([[[[2, 3, 4, 8]]]])

In [119]:
np.mat(c)

matrix([[2, 3, 4, 8]])

## np.asarray() , np.asanyarray(),   and np.array 
- all of three will change the given list into an array 
-3 of them will return almost same result only minute differces are there will dicuss below

In [66]:
np.asarray([1,5,6,9])

array([1, 5, 6, 9])

In [67]:
np.asanyarray([1,5,6,9])

array([1, 5, 6, 9])

###### Here we have passed a matrix, this is not converted into an array because matrix is subclass or sub child of array, it is not list, so this is already is fo m of array thats why this is not converted into an array again.
it will not convert if the given input is arrey in form of array, it will only change if the given input is not in form of array,

In [81]:
a=[1,2,3,4,5,6]
np.asarray(a)

array([1, 2, 3, 4, 5, 6])

In [82]:
np.mat(a)

matrix([[1, 2, 3, 4, 5, 6]])

In [83]:
np.asanyarray(a)

array([1, 2, 3, 4, 5, 6])

In [74]:
np.asanyarray(np.mat(a))        

matrix([[1, 2, 3, 4, 5, 6]])

In [75]:
a=[1,2,3,4,5,6]       
np.asanyarray(a)

array([1, 2, 3, 4, 5, 6])

## np.fromfunction()    
Helps to genrate matrixes at any point of time.

In [86]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [91]:
np.fromfunction(lambda i,j:1*j,(4,4))   #by defalut this gives u float datatype

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [98]:
np.mat(np.fromfunction(lambda i,j:1*j,(4,4))) # same result as given above

matrix([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]])

In [99]:
np.fromfunction(lambda i,j:1*j,(4,4), dtype=int)     #this will give u integer type

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [100]:
np.mat(np.fromfunction(lambda i,j:1*j,(4,4), dtype=int))

matrix([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])

### important point

In [109]:
np.fromfunction(lambda i,j,z:i*j*z,(4,2,2), dtype=int)  
# here(4,4,3) for 4 such array or matrixes of 2*2(2 rows ,2 columns) of ,the complete matrix is 3d but invid\aslly this if 2d.

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 2]],

       [[0, 0],
        [0, 3]]])

In [104]:
np.mat(np.fromfunction(lambda i,j,z:1*j*z,(4,4,3), dtype=int))   # not possible with mat() function.

ValueError: shape too large to be a matrix.

In [120]:
a=np.fromfunction(lambda i,j,z,p:i*j*z*p,(4,3,3,3), dtype=int)   #@ 4D
a
# 3 such arrays of 2x2 in 4 bundles.

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  3,  6],
         [ 0,  6, 12]],

        [[ 0,  0,  0],
         [ 0,  6, 12],
         [ 0, 12, 24]]]])

### To find the dimenstion of size, shape and datatype of an array

In [122]:
a.ndim

4

In [124]:
a.size

108

In [125]:
a.shape

(4, 3, 3, 3)

In [126]:
a.dtype


dtype('int32')

## conver(a) i.e 4D array into dataframe:
- 1. (reshaping option) we can use the pandas but pandas stored data in 2-d array, so for gthat we can reshape this and can store data into data frame
- 2. (flatterning option)

In [129]:
import pandas as pd

In [130]:
a=np.fromfunction(lambda i,j,z,p:i*j*z*p,(4,3,3,3), dtype=int)  

In [132]:
pd.DataFrame(a)     # no possible beacuse it is 4D and it pandas is 2D only 

ValueError: Must pass 2-d input. shape=(4, 3, 3, 3)

In [133]:
a=np.fromfunction(lambda i,j:i*j,(3,4), dtype=int)

In [134]:
pd.DataFrame(a)

0  1  2  3
0  0  0  0  0
1  0  1  2  3
2  0  2  4  6

In [139]:
# similarly
a= np.fromfunction(lambda i,j:i+j,(3,6),dtype=int)
a

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7]])

In [141]:
pd.DataFrame(a)

0  1  2  3  4  5
0  0  1  2  3  4  5
1  1  2  3  4  5  6
2  2  3  4  5  6  7

In [143]:
a= np.fromfunction(lambda i,j:i*j,(400,300),dtype=int)
a

array([[     0,      0,      0, ...,      0,      0,      0],
       [     0,      1,      2, ...,    297,    298,    299],
       [     0,      2,      4, ...,    594,    596,    598],
       ...,
       [     0,    397,    794, ..., 117909, 118306, 118703],
       [     0,    398,    796, ..., 118206, 118604, 119002],
       [     0,    399,    798, ..., 118503, 118902, 119301]])

In [147]:
df=pd.DataFrame(a)
df

0    1    2     3     4     5     6     7     8     9    ...     290  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     290   
2      0    2    4     6     8    10    12    14    16    18  ...     580   
3      0    3    6     9    12    15    18    21    24    27  ...     870   
4      0    4    8    12    16    20    24    28    32    36  ...    1160   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  114550   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  114840   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  115130   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  115420   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  115710   

        291     292     293     294     295     296     297     298     299  
0         0       0       0       0       0       0       0       0       0  
1       291     292     293     294     295     296     297     298     299  
2       582     584     586     588     590     592     594     596     598  
3       873     876     879     882     885     888     891     894     897  
4      1164    1168    1172    1176    1180    1184    1188    1192    1196  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  114945  115340  115735  116130  116525  116920  117315  117710  118105  
396  115236  115632  116028  116424  116820  117216  117612  118008  118404  
397  115527  115924  116321  116718  117115  117512  117909  118306  118703  
398  115818  116216  116614  117012  117410  117808  118206  118604  119002  
399  116109  116508  116907  117306  117705  118104  118503  118902  119301  

[400 rows x 300 columns]

# random function 

### rand()

In [174]:
np.random.rand(7,4)     # pass dimenstions or give shape like rows and colums 

array([[0.10005973, 0.35019683, 0.13373779, 0.92643201],
       [0.72132754, 0.04655002, 0.90528789, 0.90749134],
       [0.77800878, 0.93645351, 0.67680449, 0.17163695],
       [0.41273887, 0.23059334, 0.4643662 , 0.90545668],
       [0.31569804, 0.45055071, 0.5035292 , 0.09276288],
       [0.11860191, 0.96163834, 0.56225244, 0.47656586],
       [0.38461277, 0.96648311, 0.87945303, 0.16639892]])

## randn()

In [160]:
np.random.randn(4,5)

array([[-0.00930887, -0.48782436,  0.14203384,  1.08597144, -0.55745622],
       [-0.53992533, -0.30554364,  0.56770915,  0.04214819, -1.78536326],
       [ 0.0305785 , -0.49790289, -1.47300309,  0.54746032,  0.53972441],
       [ 0.70189539, -0.34285629,  1.73093089,  1.61473823, -0.74592351]])

## Diffence between rand() and randn()

```
1 rand - give u simple random numbers 
2 randn- gives u simple random number but with normal distribution
  2.1. average of these numbers will be-  zero(0) 
  2.2 standard daviation will be 1 only 
     

### Que- create a dataframe with normaldistribution numbers

In [165]:
a=np.random.randn(3,6)
a

array([[-0.8062299 ,  0.82786455,  2.6118731 ,  0.44357436, -0.06423779,
         0.84316157],
       [ 1.23090029, -0.02093045,  0.0167964 ,  0.21914014,  0.78079627,
        -1.10233992],
       [ 0.27038455, -1.00207968,  0.38489036, -0.02385435,  0.91482592,
        -0.04703763]])

In [166]:
pd.DataFrame(a)

0         1         2         3         4         5
0 -0.806230  0.827865  2.611873  0.443574 -0.064238  0.843162
1  1.230900 -0.020930  0.016796  0.219140  0.780796 -1.102340
2  0.270385 -1.002080  0.384890 -0.023854  0.914826 -0.047038

## randint()       # will return u random integer

In [158]:
np.random.randint(4,50)

32

# How to change dimenstions of a dataset

## reshape()

In [177]:
a= np.fromfunction(lambda i,j,z : i*j*z,(4,3,2), dtype= int)  # total number of element are 24  
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [197]:
'''
For 2D
total number of element are 24  this can be 
(1*24) or(24*1)
(12*2) or(2*12)=24 
(8*3) or (3*8)= 24

which menas any element whose multiplication is equal to 24 can reshape the array

---> we can reshape the same given data  i.e 3D into 4D.
possible combination will be 
(4,8,1,3)
(3,1,8,4)  and so on 


----> similarly we can convert this into 5-D, 6-D,7-D and so on
(4,8,1,3,1) ---> 5D
(4,1,8,1,3,1)---> 6D

'''

a.reshape(3,8)    

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3, 0, 6]])

In [198]:
a.reshape(2,12)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [201]:
n=a.reshape(6,4)

In [200]:
# now we canvert this into a dataframe.
pd.DataFrame(n)

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [208]:
a= np.fromfunction(lambda i,j,z : i*j*z,(4,3,2), dtype= int)  # total number of element are 24  
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

## very important ---->here -1 is not negative index,this can be any negative number -2,-8,-5 
- it means in (a) we have 24 elements and it will automatically take 6 in place of -1 as 4* is 6  
- which means----> 4 multiplky by number(6) is what is going to be 24


In [209]:
a.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [213]:
a.reshape(2,-1)     # it took 12 as 2*2------>> 24

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [215]:
a.reshape(2,-145695876)  #we can take any negative number

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [217]:
a.reshape(2,-2455795)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [218]:
a.reshape(2,-795)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

## simple range() and  numpy.arange()
- simple range()----> with floting numbers are not permitted -------> only integer
- numpy.arrange----> with floating number is possible 

### simple range()

In [220]:
list(range(4,10,2))

[4, 6, 8]

### simple range()---->floting numbers are not permitted -----> only integer

In [235]:
list(range(4,10,.2))    # not posiible 

TypeError: 'float' object cannot be interpreted as an integer

In [236]:
list(range(4,10.4,.2))

TypeError: 'float' object cannot be interpreted as an integer

### np.arange()

In [237]:
np.arange(4,10,2)   # every time it takes jump or step of 2. not included the last number 

array([4, 6, 8])

### numpy.arrange----> floating numbers are permitted

In [238]:
np.arange(4,10,.2)        # possible in numply arange , every time it will take jump of .2

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [240]:
a1=np.arange(4,10.4,.5)
a1

array([ 4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,
        9.5, 10. ])

### slicing operation 

In [242]:
a1[:5]

array([4. , 4.5, 5. , 5.5, 6. ])

In [245]:
arr=np.random.rand(4,5)
arr

array([[0.04914824, 0.19176344, 0.5881636 , 0.3883339 , 0.77401027],
       [0.93411635, 0.54405516, 0.68983441, 0.09624707, 0.71113149],
       [0.92423286, 0.75881787, 0.30752936, 0.80331826, 0.30325602],
       [0.74850171, 0.23160263, 0.21885976, 0.50488458, 0.79128849]])

### extract all the number greaater than .5

In [246]:
arr>.5

array([[False, False,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True, False, False,  True,  True]])

In [248]:
arr[arr>.5]

array([0.5881636 , 0.77401027, 0.93411635, 0.54405516, 0.68983441,
       0.71113149, 0.92423286, 0.75881787, 0.80331826, 0.74850171,
       0.50488458, 0.79128849])

In [249]:
arr

array([[0.04914824, 0.19176344, 0.5881636 , 0.3883339 , 0.77401027],
       [0.93411635, 0.54405516, 0.68983441, 0.09624707, 0.71113149],
       [0.92423286, 0.75881787, 0.30752936, 0.80331826, 0.30325602],
       [0.74850171, 0.23160263, 0.21885976, 0.50488458, 0.79128849]])

In [264]:
### slicing      #arr[:n-1,:n-1] or arr[row,column]

In [262]:
arr[1:5,2:5]           #arr[:n-1,:n-1]

array([[0.68983441, 0.09624707, 0.71113149],
       [0.30752936, 0.80331826, 0.30325602],
       [0.21885976, 0.50488458, 0.79128849]])

In [263]:
arr[1:3,2:3]

array([[0.68983441],
       [0.30752936]])

In [265]:
arr[[1,2],[2]]

array([0.68983441, 0.30752936])

In [266]:
arr1=np.random.rand(8,5)
arr1

array([[0.82280513, 0.09902455, 0.55291951, 0.26924352, 0.29200958],
       [0.27972453, 0.50526578, 0.92956643, 0.94277717, 0.17716858],
       [0.37821747, 0.03118093, 0.92729057, 0.86434563, 0.28917609],
       [0.40101375, 0.2291495 , 0.34135074, 0.08814821, 0.23971456],
       [0.15011648, 0.17798019, 0.95642302, 0.22067765, 0.18218398],
       [0.35275826, 0.55893224, 0.58016418, 0.62843604, 0.45368139],
       [0.7597695 , 0.31705588, 0.74702536, 0.30093407, 0.42808721],
       [0.76576775, 0.84269021, 0.24015425, 0.59437201, 0.94340711]])

In [285]:
arr1[1:8,[0,1,2,3]]

array([[0.27972453, 0.50526578, 0.92956643, 0.94277717],
       [0.37821747, 0.03118093, 0.92729057, 0.86434563],
       [0.40101375, 0.2291495 , 0.34135074, 0.08814821],
       [0.15011648, 0.17798019, 0.95642302, 0.22067765],
       [0.35275826, 0.55893224, 0.58016418, 0.62843604],
       [0.7597695 , 0.31705588, 0.74702536, 0.30093407],
       [0.76576775, 0.84269021, 0.24015425, 0.59437201]])

In [286]:
a2=arr1[1:8,0:4]
a2

array([[0.27972453, 0.50526578, 0.92956643, 0.94277717],
       [0.37821747, 0.03118093, 0.92729057, 0.86434563],
       [0.40101375, 0.2291495 , 0.34135074, 0.08814821],
       [0.15011648, 0.17798019, 0.95642302, 0.22067765],
       [0.35275826, 0.55893224, 0.58016418, 0.62843604],
       [0.7597695 , 0.31705588, 0.74702536, 0.30093407],
       [0.76576775, 0.84269021, 0.24015425, 0.59437201]])

### change the value at [0,1]

In [293]:
a2[0][1]= 189428462

In [294]:
a2

array([[2.79724533e-01, 1.89428462e+08, 9.29566435e-01, 9.42777170e-01],
       [3.78217474e-01, 3.11809302e-02, 9.27290571e-01, 8.64345634e-01],
       [4.01013754e-01, 2.29149500e-01, 3.41350738e-01, 8.81482108e-02],
       [1.50116484e-01, 1.77980189e-01, 9.56423019e-01, 2.20677655e-01],
       [3.52758260e-01, 5.58932236e-01, 5.80164176e-01, 6.28436041e-01],
       [7.59769497e-01, 3.17055880e-01, 7.47025357e-01, 3.00934071e-01],
       [7.65767753e-01, 8.42690206e-01, 2.40154252e-01, 5.94372012e-01]])

###  (@)matrix multiplcation  (column of ist array and of  row of 2nd array must be equal =  [2x3],[3,3]  

In [311]:
a11=np.array([[1,2],[3,4]])
b11=np.array([[5,6],[4,5]])

In [312]:
a11

array([[1, 2],
       [3, 4]])

In [313]:
b11

array([[2, 3],
       [4, 5]])

In [323]:
a11*b11    # ---------------> this is not matrix mukltiplication this is index multiplication 

array([[ 2,  6],
       [12, 20]])

In [316]:
a11@b11

array([[10, 13],
       [22, 29]])

In [318]:
a12=np.array([[1,2,3],[4,5,6],[7,8,9]])
a12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [321]:
b12=[[1,2],[3,4],[5,6]]
b13=np.array(b12)
b13

array([[1, 2],
       [3, 4],
       [5, 6]])

In [325]:
m=a12@b13
m

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [327]:
m/0     # it will give u infinity

C:\Users\apsgo\AppData\Local\Temp\ipykernel_4244\2596652694.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0     # it will give u infinity


array([[inf, inf],
       [inf, inf],
       [inf, inf]])